### ISSUE TITLE
Edit items

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#1]
## Value Proposition

**As a** user

**I need** to be able to edit my items

**to be able to** correct typos, select new storage place or update quantity

## Description

![image](https://user-images.githubusercontent.com/115499721/206733930-b5c62c1e-6df1-4db7-a82f-96dcedff7db4.png)

## Acceptance Criteria

- [x] each item has an edit icon
- [x] when you click on edit button, item can be updated
- [x] when item is edited a 'save changes' button is displayed
- [x] after saving the item is shown with edited details

## Tasks

- [x] add save and edit buttons to item card
- [x] add function to 'save changes' button
- [x] add function to 'edit' button
- [x] display edited state of item
- [x] style edit state of item

**Comment by esrefbozkurt** [comment]
Maybe "Best before end" ? rest looks clean and manageable.
