### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#10]
## Value Proposition

**As a** user
**I want** my items to be saved
**so that** i can see my items when opening the app again
​

## Description

- Items should be saved in local storage

​

## Acceptance Criteria

- [x] When returning to the app after closing it, all Items should still appear
- [x] Deleted items are still deleted when returning to the app
- [x] Changes made to items via edit function are saved and the item is displayed correctly when returnung
      ​

## Tasks

- [x] add local storage
- [x] save items in local storage instead of useState
      ​

**Comment by flipkoehler** [comment]
Story sieht super aus! Viel ERfolg mit dem Local Storage - das soll ja ein ganz schöner Kampf sein 😨
