### ISSUE TITLE
sort items by date

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#11]
## Value Proposition

**As a** user
**I want ** my items to be sorted by date
**so that** I can see which Items I have to use first
​

## Description

- on each page items are sorted by date automatically
​

## Acceptance Criteria

- [x] items are in correct order
- [x] new items are put at the right position
      ​

## Tasks

- [x] implement sorting function
      ​

**Comment by Elgin-Schultz** [comment]
Seems like a good idea to me, just for a better understanding what date you mean you might add "expiration" ...
