### ISSUE TITLE
Fix styling for AddForm and AddButton

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#17]
## Value Proposition
**As a** user
**I want to** be able to see all my items 
**so that** I can edit and delete all items 

## Description

- AddButton + AddForm should stick to bottom of viewport
- Itemlist can be scrolled completely and every Item on List is completely visible
​

## Acceptance Criteria

- [ ] When List is scrolled you can see every Item - when completely scrolled down, the last item is **not** covered by button!
- [ ] AddButton (and Form) is always at bottom of viewport
      ​

## Tasks

- [x] Adapt Styling to make Button + Form stick to bottom
- [x]  make Itemlist scrollable
      ​

**Comment by ufelgen** [comment]
Hey, hier ist dir deine Value Proposition abhanden gekommen :)
