### ISSUE TITLE
List of Food-Items/#1

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#2]
## Value Proposition

**As a** user

**I want** my food items to be displayed on a page

**in order to** get an overview of the food I have at home 

## Description

![image](https://user-images.githubusercontent.com/115499721/206713084-c3f89afd-1e0f-4b90-a915-013193bd3748.png)

## Acceptance Criteria

- [x] Page shows a list of items
- [x] items are displayed below each other
- [x] Page has a header with title
- [x] List can be scrolled down when there are many items

## Tasks

- [x] Create list component
- [x] Create item component
- [x] Create Header component
- [x] Add dummy Data for items
- [x] add basic layout
- [x] testing/storybook
