### ISSUE TITLE
Add storage places

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#23]
## Value Proposition

**As a**  user 
**I want** to be able to sort my items by the place they're stored in
**in order to** to see i.e. all items stored in the fridge in a separate list

## Description

![image](https://user-images.githubusercontent.com/115499721/208434425-c8f70671-aa63-4dc3-abe3-24b1fea356f3.png)

## Acceptance Criteria

- [x] When new Items are added you can select a storage place
- [x] Overview page shows places and links to them
- [x] items are displayed on their selected page
- [ ] it is visible on which page you are (not decided yet how)
- [x] You can add a new place to the list

## Tasks

- [x] add overview page for storage places
- [x] make items appear on the right page
- [x] add a back/home button to get pack to overview page
- [x] add form to create new storage place

**Comment by andy-schwedler** [comment]
Hi Neele, 

coole user story. Ich bin schon gespannt auf die Umsetzung. Eine Anmerkung habe ich:

>  it is visible on which page you are

Was genau meinst du damit? Meinst du damit die URL im Browser oder erstellst du einen Pfad?

**Comment by NeeleWaehnke** [comment]
> Hi Neele,
> 
> coole user story. Ich bin schon gespannt auf die Umsetzung. Eine Anmerkung habe ich:
> 
> > it is visible on which page you are
> 
> Was genau meinst du damit? Meinst du damit die URL im Browser oder erstellst du einen Pfad?

Ich bin mir da noch nicht sicher, ich möchte aber, dass es auf irgendeine Art und Weise sichtbar ist für den User, wo er gerade ist
