### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#25]
## Value Proposition

**As a** user
**I want** my data to be saved in a database
**so that** I can access it even if my localStorage is deleted
​

## Description

-local storage is replaced with database
​

## Acceptance Criteria

- [x] all data is saved in a database
- [x] all CRUD operations work with database
      ​

## Tasks

- [x] set up database
- [x] connect app to database
- [x] make CRUD-operations work
