### ISSUE TITLE
storage-option pt.2

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#28]
## Value Proposition

**As a** user 
**I want to** see how many items are listed in one storage -category
**so that** I have a better overview of my items
​

## Description
![image](https://user-images.githubusercontent.com/115499721/208943139-72f64d18-4bb3-4c14-8e5f-ddca536a9a70.png)

## Acceptance Criteria

- [ ] each storage-category has a field that displays the current number of items
- [ ] the number is correct
      ​

## Tasks

- [ ] adapt items-array to count entries for one storage-category
- [ ] add element that displays the number of items 
      ​
