### ISSUE TITLE
Add Button 

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#3]
## Value Proposition

**As a** user

**I want to**  add  Items to the list

**to be able to** keep track of the food I have. 

## Description

![image](https://user-images.githubusercontent.com/115499721/206716145-5335282a-a056-475c-900c-d6475b937ac3.png)

## Acceptance Criteria

- [x] Functional 'Add'-Button to create new Items
- [x] Input Form for new Items have fields for name and date (required)
- [x] Input field for date only accept date - format
- [x] added items appear on top of list

## Tasks

- [x] Add Buttons for creating an item
- [x] Write function for button to add items to list
- [x] Create input form for new items with:
           - Item name
           - item date
           - item quantity
           - save - button

**Comment by jonatsuji** [comment]
Der Schritt schaut sehr übersichtlich aus! Gehört hier zu den Dev-Tasks noch, dass du sagst wo die Items nach anlegen gespeichert werden? Sprich z.b. in einem State (Array)? Falls du das erst später machst, ignorier den Kommentar einfach :)

Sonst alles schick!

**Comment by NeeleWaehnke** [comment]
> Der Schritt schaut sehr übersichtlich aus! Gehört hier zu den Dev-Tasks noch, dass du sagst wo die Items nach anlegen gespeichert werden? Sprich z.b. in einem State (Array)? Falls du das erst später machst, ignorier den Kommentar einfach :)
> 
> Sonst alles schick!

Stimmt, die sollten schon gespeichert werden, ich habs noch hinzugefügt. Guter Hinweis!
