### ISSUE TITLE
Styling/ Homepage (Storages Overview)

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#33]
## Value Proposition
**As a** user
**I want to** have a structured homepage
**so that** using it is easy and the app is nice to look at

## Description

![image](https://user-images.githubusercontent.com/115499721/211582331-cf552fa4-03ec-4ae8-9f70-e108408d3d45.png)

​- positioning of delete/edit buttons can be different than in this scribble

## Acceptance Criteria

- [x] Landing Page looks something like the scribble
- [x] the warning page is at the top (not shown in scribble)
      ​

## Tasks

- [x] adjust styling of StoragesCard component
- [x] add Arrow button to StoragesCards that links to the page
      ​

**Comment by AntjeWalter** [comment]
If Julia would see this, she would tell you to also have the warning page in the scribble and the edit and delete buttons on every element but I guess it's fine for now ;) Looks pretty good, I like the new layout!
