### ISSUE TITLE
Delete and Edit Storage-options

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#34]
## Value Proposition

**As a** user
**I want to** be able to delete or edit my storage-options
**so that** I don't have options listed I don't need anymore or fix spelling errors
​

## Description
![image](https://user-images.githubusercontent.com/115499721/210584703-a88019d6-ffe6-419b-b0ce-5c480355850c.png)

​

## Acceptance Criteria

- [ ] when an option is edited Items stay in List
- [ ] options can be deleted
- [ ] options with items listed can't be deleted
      ​

## Tasks

- [ ] add edit function to storages
- [ ] add delete function to storages
      ​

**Comment by flipkoehler** [comment]
Hey Neele, 
looks good - just some minor remarks :) 
maybe you can add some information to the edit function (e.g. What is happing when the user clicks on the edit button - where is the save button?) Also - does the user get any feedback when deleting a post?
