### ISSUE TITLE
Category Filter

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#37]
## Value Proposition

**As a** user
**I want to** be able to filter my items by my categories
**so that** I can easily see all items for one category
​

## Description

![image](https://user-images.githubusercontent.com/115499721/207086960-27ca0111-c7a0-4956-b588-cacd52816ee4.png)

​

## Acceptance Criteria

- [ ] user is able to filter by categories
- [ ] the right items are displayed
      ​

## Tasks

- [ ] add filter button
- [ ] add function to filter items
      ​

**Comment by KirstenSchuhmann** [comment]
Hi Neele :) 

ist die Filter Option dann immer auf jeder Seite je Storage Option (Fridge, Freezer, Pantry), mit Kategorien  z.Bsp. "Milchprodukte, Gemüse, etc", so dass diese gefiltert werden oder wird deine Filter Option auf der Hauptseite dargestellt und man kann zwei Filter, Storage Option & Kategorie, setzen? 

Da bin ich mir noch nicht sicher, ob ich das richtig verstanden habe. Ich würde dass in der Acceptance Criteria etwas detaillierter festlegen und die Aufgaben dann entsprechend anpassen.

**Comment by NeeleWaehnke** [comment]
> Hi Neele :)
> 
> ist die Filter Option dann immer auf jeder Seite je Storage Option (Fridge, Freezer, Pantry), mit Kategorien z.Bsp. "Milchprodukte, Gemüse, etc", so dass diese gefiltert werden oder wird deine Filter Option auf der Hauptseite dargestellt und man kann zwei Filter, Storage Option & Kategorie, setzen?
> 
> Da bin ich mir noch nicht sicher, ob ich das richtig verstanden habe. Ich würde dass in der Acceptance Criteria etwas detaillierter festlegen und die Aufgaben dann entsprechend anpassen.

Hey Kirsten, danke für den Hinweis :) ich hab das nochmal angepasst

**Comment by KirstenSchuhmann** [comment]
Ok super! :) ✅ Haken ist gesetzt :)
