### ISSUE TITLE
Menu & Navigation

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#38]
## Value Proposition

**As a** user
**I want to** have a menu
**so that** I can navigate between pages directly
​

## Description

![image](https://user-images.githubusercontent.com/115499721/211287040-1b39833f-1295-42ef-9409-5701864f8990.png)

​

## Acceptance Criteria

- [ ] user can switch between pages without going back to home page
- [ ] the menu shows the storages the user has created
      ​

## Tasks

- [ ] add menu component with navigation
- [ ] style the menu
      ​

**Comment by ufelgen** [comment]
Hi Neele, coole Idee! Ich glaube ich hätte noch ein paar mehr Aufzählungen geschrieben, z.B. dass als Links die Storages angezeigt werden, die man angelegt hat. Und in deinem Scribble sieht es so aus, als würde die Seite, auf der man sich befindet (hier Fridge, oder?) nicht in der Navigation angezeigt werden, das würde ich auch noch als Text mit einbauen. Vielleicht hab ich das aber auch falsch verstanden.
