### ISSUE TITLE
Warning-Page

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#4]
## Value Proposition

**As a** user

**I want** items that are close to the 'Best before' date to be highlighted and can be found on separate page

**to be able to** see which items I have to use soon

## Description

![image](https://user-images.githubusercontent.com/115499721/208437569-2a8c23d2-9dbf-4eca-8b03-574eab5426c0.png)

![image](https://user-images.githubusercontent.com/115499721/208444669-4f554908-88c2-4383-b960-386dee624aa5.png)

## Acceptance Criteria

- [x] You can navigate to overview page
- [x] it is possible to go back to home page

## Tasks

- [x] Create page for items that are close to their best before date
- [x] add button to go to warning page

**Comment by flipkoehler** [comment]
well done :)
