### ISSUE TITLE
log in

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#40]
## Value Proposition

**As a** user
**I want to** be able to log in
**so that** only I can access my data
​

## Description

-there is a log-in & log out button on homepage
​

## Acceptance Criteria

- [x] data is saved to logged in account
- [x] data is only visible when logged in
      ​

## Tasks

- [x] add log in with next-auth
- [x] connect log in with database 
      ​
