### ISSUE TITLE
It's the final styling!

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#41]
## Value Proposition

**As a** user
**I want to** have a nice looking app
**so that** I can enjoy using it
​

## Description

![Image](https://user-images.githubusercontent.com/115499721/212291295-4df82fff-3a73-4dcf-bb38-21bf12c45480.png)

​

## Acceptance Criteria

- [x] styling looks like the scribbles/ is consistent with colors/layout
- [x] layout fits to mobile screen     

## Tasks

- [x] style the components that aren't finished yet
- [x] add the disclaimers from scribble
      ​

**Comment by Elgin-Schultz** [comment]
I am very looking forward to seeing your styling in action. (Just wondering (NO MUST) if some icons maybe like snowflakes for freezer, ... would give some variety to the look?)
