### ISSUE TITLE
Add some A11y

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#46]
## Value Proposition

**As a** developer
**I want to** make sure that my app is accessible
**so that** everyone can use it
​

## Description

...
​

## Acceptance Criteria

- [x] Accessibility score in Lighthouse is 90+
      ​

## Tasks

- [x] add aria labels to buttons
- [x] check if forms are accessible, if not add aria-labels
- [x] check html structure (headings, too many divs etc)
      ​

**Comment by AntjeWalter** [comment]
Maybe include checking for correct html elements :) like the heading structure h1-h6
