### ISSUE TITLE
Storage - Place Option

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#5]
## Value Proposition

**As a**  user 
**I want** to be able to structure my items

** in order to** to see i.e. all items stored in the fridge in a separate list

## Description

![image](https://user-images.githubusercontent.com/115499721/206729067-8692ee3b-a593-4efe-8b5a-043ef5a4897a.png)

- Items need option to select storage place now!

## Acceptance Criteria

- [ ] When Items are created you have the option to select the storage place
- [ ] the storage place selection is required
- [ ] user is able to navigate to fridge, freezer and storage site
- [ ] items are displayed in their selected storage page

## Tasks

- [ ] add pages for fridge, freezer and storage
- [ ] add 'storage place' selection, that is required, to create item field
- [ ] make items appear on the right page

**Comment by flipkoehler** [comment]
Hey Neele, 
super User Story - die Qualität ist echt hoch 👍 
Eine Idee dazu: wenn du die Story noch verkleinern willst, könntest du die Navigation als eigene Story machen. Dort könntest du auch noch beschreiben was z.B. wenn ein Navigationspunkt aktiv ist (wird fett markiert etc...)

**Comment by NeeleWaehnke** [comment]
Hey Philip, danke für die Rückmeldung! Ich hatte eigentlich eine andere User Story, die vor der hier kommen sollte und da stand auch drin, dass es sichtbar sein soll, welcher Punkt ausgewählt ist. Ich füg das hier auch mal ein.
Ich hoffe, die US wird nicht zu groß, aber nur Navigation ohne zweite Seite oder eine zweite Seite ohne Möglichkeit zu switchen wäre ja nicht funktional, deshalb hab ich das zusammengefasst :)
