### ISSUE TITLE
Delete-Button

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#6]
## Value Proposition

**As a** user
**I want to** be able to remove items from my list
**in order to** keep my list up to date.
​

## Description

![image](https://user-images.githubusercontent.com/115499721/207068637-b99a1d6d-fe97-43cc-ba00-4fe0c34b0811.png)
​

## Acceptance Criteria

- [ ] every Item displayed has a delete button
- [ ] Any Item can be removed when delete button is clicked

      ​

## Tasks

- [ ] Add delete button to item-cards
- [ ] Write function to remove cards from list

      ​

**Comment by esrefbozkurt** [comment]
Good structure, manageable workload. Typo at item 3.
