### ISSUE TITLE
Storage-Option for Freezer

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#7]
## Value Proposition

**As a** user
**I want to** have a separate list for items in my freezer
**so that** I have an even better overview of my items
​

## Description

![image](https://user-images.githubusercontent.com/115499721/207072630-37d25e08-ad50-460e-a050-5e0f2d8c0422.png)
​

## Acceptance Criteria

- [ ] user can navigate to freezer-page
- [ ] When creating an item freezer or fridge can be selected
- [ ] the selected items are shown on the right page
      ​

## Tasks

- [ ] Create page for freezer
- [ ] Add option for freezer when selecting storage place
- [ ] add freezer link to navigation
      ​
