### ISSUE TITLE
Storage-Option Pantry

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#8]
## Value Proposition

**As a** user
**I want to** keep track of items that don't belong in the fridge/freezer too
**so that** I can add any food items to the app
​

## Description

![image](https://user-images.githubusercontent.com/115499721/207073826-1af9c84f-ba1c-4584-b384-9ad0a506547d.png)

## Acceptance Criteria

- [ ] user can navigate to pantry page
- [ ] items are correctly displayed on their storage-pages
- [ ] user can select pantry option
      ​

## Tasks

- [ ] Create page for pantry
- [ ] add pantry option for create item
- [ ] add pantry link to navigation
- [ ] add styling to navigation
      ​
