### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/capstone-project#9]
## Value Proposition

**As a** user
**I want to** have categories to sort my items
**so that** I can structure my Items

## Description

![image](https://user-images.githubusercontent.com/115499721/207086960-27ca0111-c7a0-4956-b588-cacd52816ee4.png)
​

## Acceptance Criteria

- [ ] user can select a category for items
- [ ] user can create new categories 
- [ ] user can pick a category when creating an item
      ​

## Tasks

- [ ] create dummy-options for categories
- [ ] add form to create new categories
- [ ] add category option to create-item form

      ​
